spring.datasource.url=jdbc:postgresql://dpg-d5vm8u4oud1c738marf0-a.virginia-postgres.render.com:5432/hirelog_db
spring.datasource.username=hirelog_db_user
spring.datasource.password=PHbz9MAtDpQXdNWvYGFcfqgZjRqozqAQ

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

# REQUIRED for Render
spring.datasource.hikari.ssl=true
spring.datasource.hikari.sslmode=require

# Hibernate Dialect (VERY IMPORTANT)
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
